// Package licensingapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package licensingapi

import (
	"github.com/timrabl/terraform-provider-snipeit/internal/client"
)

// DateObject Nested date, e.g. {"date": "2026-01-10", "formatted": "..."}.
type DateObject = client.Date

// FlexBool Boolean the API may return as true/false, 0/1 or "0"/"1".
type FlexBool = client.FlexBool

// FlexInt Integer the API may return as a bare number, a numeric string, or a decorated string.
type FlexInt = client.FlexInt

// License defines model for License.
type License struct {
	// Category Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Category *NestedRef `json:"category,omitempty"`

	// Company Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Company *NestedRef `json:"company,omitempty"`

	// ExpirationDate Nested date, e.g. {"date": "2026-01-10", "formatted": "..."}.
	ExpirationDate *DateObject `json:"expiration_date,omitempty"`

	// FreeSeatsCount Integer the API may return as a bare number, a numeric string, or a decorated string.
	FreeSeatsCount FlexInt `json:"free_seats_count"`
	Id             int64   `json:"id"`
	LicenseEmail   *string `json:"license_email,omitempty"`
	LicenseName    *string `json:"license_name,omitempty"`

	// Maintained Boolean the API may return as true/false, 0/1 or "0"/"1".
	Maintained FlexBool `json:"maintained"`

	// Manufacturer Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Manufacturer *NestedRef `json:"manufacturer,omitempty"`
	Name         string     `json:"name"`
	Notes        *string    `json:"notes,omitempty"`
	OrderNumber  *string    `json:"order_number,omitempty"`

	// ProductKey GET-side name of the write field `serial`.
	ProductKey   *string `json:"product_key,omitempty"`
	PurchaseCost *string `json:"purchase_cost,omitempty"`

	// PurchaseDate Nested date, e.g. {"date": "2026-01-10", "formatted": "..."}.
	PurchaseDate  *DateObject `json:"purchase_date,omitempty"`
	PurchaseOrder *string     `json:"purchase_order,omitempty"`

	// Reassignable Boolean the API may return as true/false, 0/1 or "0"/"1".
	Reassignable FlexBool `json:"reassignable"`

	// Seats Integer the API may return as a bare number, a numeric string, or a decorated string.
	Seats FlexInt `json:"seats"`

	// Supplier Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Supplier *NestedRef `json:"supplier,omitempty"`

	// TerminationDate Nested date, e.g. {"date": "2026-01-10", "formatted": "..."}.
	TerminationDate *DateObject `json:"termination_date,omitempty"`
}

// LicenseList defines model for LicenseList.
type LicenseList struct {
	Rows  []License `json:"rows"`
	Total int64     `json:"total"`
}

// LicenseSeat defines model for LicenseSeat.
type LicenseSeat struct {
	// AssignedAsset Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	AssignedAsset *NestedRef `json:"assigned_asset,omitempty"`

	// AssignedUser Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	AssignedUser *NestedRef `json:"assigned_user,omitempty"`
	Id           int64      `json:"id"`
	LicenseId    int64      `json:"license_id"`
}

// LicenseSeatList defines model for LicenseSeatList.
type LicenseSeatList struct {
	Rows  []LicenseSeat `json:"rows"`
	Total int64         `json:"total"`
}

// NestedRef Nested related-object reference, e.g. {"id": 3, "name": "X"}.
type NestedRef = client.Ref

// Id defines model for id.
type Id = int64

// SeatId defines model for seat_id.
type SeatId = int64
