// Package assetsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package assetsapi

import (
	"github.com/timrabl/terraform-provider-snipeit/internal/client"
)

// Category category_type arrives capitalized ("Asset"); the provider normalizes to lowercase. eula_text is write-only and never returned.
type Category struct {
	CategoryType string `json:"category_type"`

	// CheckinEmail Boolean that the API may serialize as true/false, 0/1 or "0"/"1".
	CheckinEmail FlexBool `json:"checkin_email"`

	// Eula Boolean that the API may serialize as true/false, 0/1 or "0"/"1".
	Eula  FlexBool `json:"eula"`
	Id    int64    `json:"id"`
	Name  string   `json:"name"`
	Notes *string  `json:"notes,omitempty"`

	// RequireAcceptance Boolean that the API may serialize as true/false, 0/1 or "0"/"1".
	RequireAcceptance FlexBool `json:"require_acceptance"`

	// UseDefaultEula Boolean that the API may serialize as true/false, 0/1 or "0"/"1".
	UseDefaultEula FlexBool `json:"use_default_eula"`
}

// CategoryList defines model for CategoryList.
type CategoryList struct {
	Rows  []Category `json:"rows"`
	Total int64      `json:"total"`
}

// FlexBool Boolean that the API may serialize as true/false, 0/1 or "0"/"1".
type FlexBool = client.FlexBool

// FlexInt Integer that the API may serialize as 24, "24", "24 mo." or "24 months"; null decodes to 0.
type FlexInt = client.FlexInt

// Hardware The default (ready-to-deploy) location is READ as rtd_location but WRITTEN as rtd_location_id.
type Hardware struct {
	AssetTag string `json:"asset_tag"`

	// Company Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Company *NestedRef `json:"company,omitempty"`

	// DeletedAt Nested timestamp, e.g. {"datetime": "2026-01-15 12:00:00", "formatted": "..."}.
	DeletedAt *NestedDateTime `json:"deleted_at,omitempty"`
	Id        int64           `json:"id"`

	// Model Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Model       *NestedRef `json:"model,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Notes       *string    `json:"notes,omitempty"`
	OrderNumber *string    `json:"order_number,omitempty"`

	// PurchaseDate Nested date, e.g. {"date": "2026-01-15", "formatted": "..."}.
	PurchaseDate *NestedDate `json:"purchase_date,omitempty"`

	// Requestable Boolean that the API may serialize as true/false, 0/1 or "0"/"1".
	Requestable FlexBool `json:"requestable"`

	// RtdLocation Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	RtdLocation *NestedRef `json:"rtd_location,omitempty"`
	Serial      *string    `json:"serial,omitempty"`

	// StatusLabel Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	StatusLabel *NestedRef `json:"status_label,omitempty"`

	// Supplier Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Supplier *NestedRef `json:"supplier,omitempty"`

	// WarrantyMonths Integer that the API may serialize as 24, "24", "24 mo." or "24 months"; null decodes to 0.
	WarrantyMonths FlexInt `json:"warranty_months"`
}

// HardwareList defines model for HardwareList.
type HardwareList struct {
	Rows  []Hardware `json:"rows"`
	Total int64      `json:"total"`
}

// Manufacturer Plain-string fields (url, support_*) are always present; the API sends "" or null interchangeably for unset — both decode to the empty string.
type Manufacturer struct {
	Id                int64   `json:"id"`
	Name              string  `json:"name"`
	Notes             *string `json:"notes,omitempty"`
	SupportEmail      string  `json:"support_email"`
	SupportPhone      string  `json:"support_phone"`
	SupportUrl        string  `json:"support_url"`
	Url               string  `json:"url"`
	WarrantyLookupUrl string  `json:"warranty_lookup_url"`
}

// ManufacturerList defines model for ManufacturerList.
type ManufacturerList struct {
	Rows  []Manufacturer `json:"rows"`
	Total int64          `json:"total"`
}

// Model defines model for Model.
type Model struct {
	// Category Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Category *NestedRef `json:"category,omitempty"`

	// Eol Integer that the API may serialize as 24, "24", "24 mo." or "24 months"; null decodes to 0.
	Eol FlexInt `json:"eol"`

	// Fieldset Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Fieldset *NestedRef `json:"fieldset,omitempty"`
	Id       int64      `json:"id"`

	// Manufacturer Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Manufacturer *NestedRef `json:"manufacturer,omitempty"`

	// MinAmt Integer that the API may serialize as 24, "24", "24 mo." or "24 months"; null decodes to 0.
	MinAmt      FlexInt `json:"min_amt"`
	ModelNumber *string `json:"model_number,omitempty"`
	Name        string  `json:"name"`
	Notes       *string `json:"notes,omitempty"`

	// Requestable Boolean that the API may serialize as true/false, 0/1 or "0"/"1".
	Requestable FlexBool `json:"requestable"`
}

// ModelList defines model for ModelList.
type ModelList struct {
	Rows  []Model `json:"rows"`
	Total int64   `json:"total"`
}

// NestedDate Nested date, e.g. {"date": "2026-01-15", "formatted": "..."}.
type NestedDate = client.Date

// NestedDateTime Nested timestamp, e.g. {"datetime": "2026-01-15 12:00:00", "formatted": "..."}.
type NestedDateTime = client.DateTime

// NestedRef Nested related-object reference, e.g. {"id": 3, "name": "X"}.
type NestedRef = client.Ref

// StatusLabel type arrives capitalized; the provider normalizes to lowercase.
type StatusLabel struct {
	Color *string `json:"color,omitempty"`

	// DefaultLabel Boolean that the API may serialize as true/false, 0/1 or "0"/"1".
	DefaultLabel FlexBool `json:"default_label"`
	Id           int64    `json:"id"`
	Name         string   `json:"name"`
	Notes        *string  `json:"notes,omitempty"`

	// ShowInNav Boolean that the API may serialize as true/false, 0/1 or "0"/"1".
	ShowInNav FlexBool `json:"show_in_nav"`
	Type      string   `json:"type"`
}

// StatusLabelList defines model for StatusLabelList.
type StatusLabelList struct {
	Rows  []StatusLabel `json:"rows"`
	Total int64         `json:"total"`
}

// Id defines model for id.
type Id = int64
