// Package organizationapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package organizationapi

import (
	"github.com/timrabl/terraform-provider-snipeit/internal/client"
)

// Company defines model for Company.
type Company struct {
	Email *string `json:"email,omitempty"`
	Fax   *string `json:"fax,omitempty"`
	Id    int64   `json:"id"`
	Name  string  `json:"name"`
	Notes *string `json:"notes,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

// CompanyList defines model for CompanyList.
type CompanyList struct {
	Rows  []Company `json:"rows"`
	Total int64     `json:"total"`
}

// Department defines model for Department.
type Department struct {
	// Company Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Company *NestedRef `json:"company,omitempty"`
	Id      int64      `json:"id"`

	// Location Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Location *NestedRef `json:"location,omitempty"`

	// Manager Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Manager *NestedRef `json:"manager,omitempty"`
	Name    string     `json:"name"`
	Notes   *string    `json:"notes,omitempty"`
}

// DepartmentList defines model for DepartmentList.
type DepartmentList struct {
	Rows  []Department `json:"rows"`
	Total int64        `json:"total"`
}

// Location defines model for Location.
type Location struct {
	Address  *string `json:"address,omitempty"`
	Address2 *string `json:"address2,omitempty"`
	City     *string `json:"city,omitempty"`
	Country  *string `json:"country,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Fax      *string `json:"fax,omitempty"`
	Id       int64   `json:"id"`
	LdapOu   *string `json:"ldap_ou,omitempty"`

	// Manager Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Manager *NestedRef `json:"manager,omitempty"`
	Name    string     `json:"name"`
	Notes   *string    `json:"notes,omitempty"`

	// Parent Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Parent *NestedRef `json:"parent,omitempty"`
	Phone  *string    `json:"phone,omitempty"`
	State  *string    `json:"state,omitempty"`
	Zip    *string    `json:"zip,omitempty"`
}

// LocationList defines model for LocationList.
type LocationList struct {
	Rows  []Location `json:"rows"`
	Total int64      `json:"total"`
}

// NestedRef Nested related-object reference, e.g. {"id": 3, "name": "X"}.
type NestedRef = client.Ref

// Supplier defines model for Supplier.
type Supplier struct {
	Address  *string `json:"address,omitempty"`
	Address2 *string `json:"address2,omitempty"`
	City     *string `json:"city,omitempty"`
	Contact  *string `json:"contact,omitempty"`
	Country  *string `json:"country,omitempty"`
	Email    *string `json:"email,omitempty"`
	Fax      *string `json:"fax,omitempty"`
	Id       int64   `json:"id"`
	Name     string  `json:"name"`
	Notes    *string `json:"notes,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	State    *string `json:"state,omitempty"`
	Url      *string `json:"url,omitempty"`
	Zip      *string `json:"zip,omitempty"`
}

// SupplierList defines model for SupplierList.
type SupplierList struct {
	Rows  []Supplier `json:"rows"`
	Total int64      `json:"total"`
}

// Id defines model for id.
type Id = int64
