// Package customfieldsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package customfieldsapi

import (
	"github.com/timrabl/terraform-provider-snipeit/internal/client"
)

// Field Custom field detail. The form element is exposed under `type`; help_text and show_in_email are write-only and never appear here.
type Field struct {
	// DbColumnName Server-derived from the name; changes on rename.
	DbColumnName string `json:"db_column_name"`

	// FieldValues Selectable values, one per line.
	FieldValues *string `json:"field_values,omitempty"`

	// Format One of the 13 presets; regexes are stored as ANY.
	Format string `json:"format"`
	Id     int64  `json:"id"`
	Name   string `json:"name"`

	// Element Form element (text, textarea, listbox, checkbox, radio).
	Element string `json:"type"`
}

// FieldList defines model for FieldList.
type FieldList struct {
	Rows  []Field `json:"rows"`
	Total int64   `json:"total"`
}

// Fieldset defines model for Fieldset.
type Fieldset struct {
	Fields FieldsetFieldList `json:"fields"`
	Id     int64             `json:"id"`
	Name   string            `json:"name"`
}

// FieldsetField A field row as embedded in a fieldset detail response.
type FieldsetField struct {
	DbColumnName string `json:"db_column_name"`
	Format       string `json:"format"`
	Id           int64  `json:"id"`
	Name         string `json:"name"`

	// Required Boolean the API returns as true/false, 0/1 or "0"/"1".
	Required FlexBool `json:"required"`
	Element  string   `json:"type"`
}

// FieldsetFieldList defines model for FieldsetFieldList.
type FieldsetFieldList struct {
	Rows []FieldsetField `json:"rows"`
}

// FieldsetList defines model for FieldsetList.
type FieldsetList struct {
	Rows  []Fieldset `json:"rows"`
	Total int64      `json:"total"`
}

// FlexBool Boolean the API returns as true/false, 0/1 or "0"/"1".
type FlexBool = client.FlexBool

// Id defines model for id.
type Id = int64
