// Package peopleapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package peopleapi

import (
	"github.com/timrabl/terraform-provider-snipeit/internal/client"
)

// Group defines model for Group.
type Group struct {
	Id    int64   `json:"id"`
	Name  string  `json:"name"`
	Notes *string `json:"notes,omitempty"`

	// Permissions Stored permission map, values "1" (allow), "0" (inherit/deny) or "-1" (explicit deny). Groups created without permissions get a server-generated full default map. Values are string-encoded on Snipe-IT <= 8.0 ("0"/"1") but bare numbers on 8.4+; FlexString tolerates both.
	Permissions map[string]client.FlexString `json:"permissions"`
}

// GroupList defines model for GroupList.
type GroupList struct {
	Rows  []Group `json:"rows"`
	Total int64   `json:"total"`
}

// NestedRef Nested related-object reference, e.g. {"id": 3, "name": "X"}.
type NestedRef = client.Ref

// User defines model for User.
type User struct {
	Activated bool `json:"activated"`

	// Company Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Company *NestedRef `json:"company,omitempty"`

	// Department Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Department  *NestedRef `json:"department,omitempty"`
	Email       *string    `json:"email,omitempty"`
	EmployeeNum *string    `json:"employee_num,omitempty"`
	FirstName   string     `json:"first_name"`

	// Groups Group memberships of a user as returned inline on the user object.
	Groups   *UserGroups `json:"groups,omitempty"`
	Id       int64       `json:"id"`
	Jobtitle *string     `json:"jobtitle,omitempty"`
	LastName *string     `json:"last_name,omitempty"`

	// Location Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Location *NestedRef `json:"location,omitempty"`

	// Manager Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Manager  *NestedRef `json:"manager,omitempty"`
	Notes    *string    `json:"notes,omitempty"`
	Phone    *string    `json:"phone,omitempty"`
	Username string     `json:"username"`
}

// UserGroups Group memberships of a user as returned inline on the user object.
type UserGroups struct {
	Rows  []NestedRef `json:"rows"`
	Total *int64      `json:"total,omitempty"`
}

// UserList defines model for UserList.
type UserList struct {
	Rows  []User `json:"rows"`
	Total int64  `json:"total"`
}

// UserWriteBody Documentation-only model of the user create/update body. The provider builds request maps (clear-on-unset semantics per field); this schema exists to document the write-only password contract.
type UserWriteBody struct {
	FirstName string `json:"first_name"`

	// Groups Written as a plain array of group ids (read shape differs, see UserGroups).
	Groups *[]int64 `json:"groups,omitempty"`

	// Password Write-only. Required by the API on create, never returned by any endpoint. Sent together with password_confirmation.
	Password *string `json:"password,omitempty"`

	// PasswordConfirmation Write-only, must equal password.
	PasswordConfirmation *string `json:"password_confirmation,omitempty"`
	Username             string  `json:"username"`
}

// Id defines model for id.
type Id = int64

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserWriteBody
