// Package inventoryapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package inventoryapi

import (
	"github.com/timrabl/terraform-provider-snipeit/internal/client"
)

// Accessory defines model for Accessory.
type Accessory struct {
	// Category Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Category *NestedRef `json:"category,omitempty"`

	// Company Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Company *NestedRef `json:"company,omitempty"`
	Id      int64      `json:"id"`

	// Location Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Location *NestedRef `json:"location,omitempty"`

	// Manufacturer Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Manufacturer *NestedRef `json:"manufacturer,omitempty"`

	// MinQty Read-serializer name of the write field min_amt.
	MinQty       FlexInt `json:"min_qty"`
	ModelNumber  *string `json:"model_number,omitempty"`
	Name         string  `json:"name"`
	Notes        *string `json:"notes,omitempty"`
	OrderNumber  *string `json:"order_number,omitempty"`
	PurchaseCost *string `json:"purchase_cost,omitempty"`

	// PurchaseDate Nested date, e.g. {"date": "2026-01-10", "formatted": "..."}.
	PurchaseDate *DateObject `json:"purchase_date,omitempty"`

	// Qty Integer the API may serialize as 24, "24" or "24 mo.".
	Qty FlexInt `json:"qty"`

	// Supplier Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Supplier *NestedRef `json:"supplier,omitempty"`
}

// AccessoryCheckoutList defines model for AccessoryCheckoutList.
type AccessoryCheckoutList struct {
	Rows  []AccessoryCheckoutRow `json:"rows"`
	Total int64                  `json:"total"`
}

// AccessoryCheckoutRow defines model for AccessoryCheckoutRow.
type AccessoryCheckoutRow struct {
	// AssignedTo Polymorphic assignment target of a checkout row.
	AssignedTo *AssignedTarget `json:"assigned_to,omitempty"`

	// Id Pivot row id — the checkin target.
	Id int64 `json:"id"`
}

// AccessoryList defines model for AccessoryList.
type AccessoryList struct {
	Rows  []Accessory `json:"rows"`
	Total int64       `json:"total"`
}

// AssignedTarget Polymorphic assignment target of a checkout row.
type AssignedTarget struct {
	Id int64 `json:"id"`

	// Type user, asset or location
	Type string `json:"type"`
}

// Component defines model for Component.
type Component struct {
	// Category Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Category *NestedRef `json:"category,omitempty"`

	// Company Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Company *NestedRef `json:"company,omitempty"`
	Id      int64      `json:"id"`

	// Location Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Location *NestedRef `json:"location,omitempty"`

	// MinAmt Integer the API may serialize as 24, "24" or "24 mo.".
	MinAmt       FlexInt `json:"min_amt"`
	Name         string  `json:"name"`
	Notes        *string `json:"notes,omitempty"`
	OrderNumber  *string `json:"order_number,omitempty"`
	PurchaseCost *string `json:"purchase_cost,omitempty"`

	// PurchaseDate Nested date, e.g. {"date": "2026-01-10", "formatted": "..."}.
	PurchaseDate *DateObject `json:"purchase_date,omitempty"`

	// Qty Integer the API may serialize as 24, "24" or "24 mo.".
	Qty    FlexInt `json:"qty"`
	Serial *string `json:"serial,omitempty"`

	// Supplier Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Supplier *NestedRef `json:"supplier,omitempty"`
}

// ComponentAssetList defines model for ComponentAssetList.
type ComponentAssetList struct {
	Rows  []ComponentAssetRow `json:"rows"`
	Total int64               `json:"total"`
}

// ComponentAssetRow defines model for ComponentAssetRow.
type ComponentAssetRow struct {
	// AssignedPivotId Pivot row id — the checkin target.
	AssignedPivotId int64 `json:"assigned_pivot_id"`

	// Id Id of the asset holding the units.
	Id int64 `json:"id"`

	// Qty Integer the API may serialize as 24, "24" or "24 mo.".
	Qty FlexInt `json:"qty"`
}

// ComponentList defines model for ComponentList.
type ComponentList struct {
	Rows  []Component `json:"rows"`
	Total int64       `json:"total"`
}

// Consumable defines model for Consumable.
type Consumable struct {
	// Category Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Category *NestedRef `json:"category,omitempty"`

	// Company Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Company *NestedRef `json:"company,omitempty"`
	Id      int64      `json:"id"`
	ItemNo  *string    `json:"item_no,omitempty"`

	// Location Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Location *NestedRef `json:"location,omitempty"`

	// Manufacturer Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Manufacturer *NestedRef `json:"manufacturer,omitempty"`

	// MinAmt Integer the API may serialize as 24, "24" or "24 mo.".
	MinAmt       FlexInt `json:"min_amt"`
	ModelNumber  *string `json:"model_number,omitempty"`
	Name         string  `json:"name"`
	Notes        *string `json:"notes,omitempty"`
	OrderNumber  *string `json:"order_number,omitempty"`
	PurchaseCost *string `json:"purchase_cost,omitempty"`

	// PurchaseDate Nested date, e.g. {"date": "2026-01-10", "formatted": "..."}.
	PurchaseDate *DateObject `json:"purchase_date,omitempty"`

	// Qty Integer the API may serialize as 24, "24" or "24 mo.".
	Qty FlexInt `json:"qty"`
}

// ConsumableList defines model for ConsumableList.
type ConsumableList struct {
	Rows  []Consumable `json:"rows"`
	Total int64        `json:"total"`
}

// DateObject Nested date, e.g. {"date": "2026-01-10", "formatted": "..."}.
type DateObject = client.Date

// FlexInt Integer the API may serialize as 24, "24" or "24 mo.".
type FlexInt = client.FlexInt

// HardwareAssignment defines model for HardwareAssignment.
type HardwareAssignment struct {
	// AssignedTo Polymorphic assignment target of a checkout row.
	AssignedTo *AssignedTarget `json:"assigned_to,omitempty"`
	Id         int64           `json:"id"`
}

// NestedRef Nested related-object reference, e.g. {"id": 3, "name": "X"}.
type NestedRef = client.Ref

// Id defines model for id.
type Id = int64

// Pivot defines model for pivot.
type Pivot = int64
