// Package operationsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package operationsapi

import (
	"github.com/timrabl/terraform-provider-snipeit/internal/client"
)

// ActivityAdmin defines model for ActivityAdmin.
type ActivityAdmin struct {
	Name string `json:"name"`
}

// ActivityItem defines model for ActivityItem.
type ActivityItem struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// ActivityList defines model for ActivityList.
type ActivityList struct {
	Rows  []ActivityRow `json:"rows"`
	Total int64         `json:"total"`
}

// ActivityRow defines model for ActivityRow.
type ActivityRow struct {
	// ActionDate Nested timestamp shape {"datetime": "...", "formatted": "..."}.
	ActionDate *NestedDateTime `json:"action_date,omitempty"`
	ActionType string          `json:"action_type"`
	Admin      *ActivityAdmin  `json:"admin,omitempty"`
	Id         int64           `json:"id"`
	Item       *ActivityItem   `json:"item,omitempty"`
	Note       *string         `json:"note,omitempty"`
	Target     *ActivityItem   `json:"target,omitempty"`
}

// AuditList defines model for AuditList.
type AuditList struct {
	Rows  []AuditRow `json:"rows"`
	Total int64      `json:"total"`
}

// AuditRow defines model for AuditRow.
type AuditRow struct {
	AssetTag string  `json:"asset_tag"`
	Id       int64   `json:"id"`
	Name     *string `json:"name,omitempty"`
}

// FlexBool Boolean the API returns as true/false, 0/1 or "0"/"1".
type FlexBool = client.FlexBool

// Maintenance Maintenance detail. The locale-formatted `cost` is intentionally not modeled (cannot round-trip).
type Maintenance struct {
	// Asset Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Asset *NestedRef `json:"asset,omitempty"`

	// AssetMaintenanceType Not validated server-side; any string is stored.
	AssetMaintenanceType string `json:"asset_maintenance_type"`

	// CompletionDate Nested date shape {"date": "2020-01-01", "formatted": "..."}.
	CompletionDate *NestedDate `json:"completion_date,omitempty"`
	Id             int64       `json:"id"`

	// IsWarranty Boolean the API returns as true/false, 0/1 or "0"/"1".
	IsWarranty FlexBool `json:"is_warranty"`
	Notes      *string  `json:"notes,omitempty"`

	// StartDate Nested date shape {"date": "2020-01-01", "formatted": "..."}.
	StartDate *NestedDate `json:"start_date,omitempty"`

	// Supplier Nested related-object reference, e.g. {"id": 3, "name": "X"}.
	Supplier *NestedRef `json:"supplier,omitempty"`
	Title    string     `json:"title"`
}

// MaintenanceList defines model for MaintenanceList.
type MaintenanceList struct {
	Rows  []Maintenance `json:"rows"`
	Total int64         `json:"total"`
}

// NestedDate Nested date shape {"date": "2020-01-01", "formatted": "..."}.
type NestedDate = client.Date

// NestedDateTime Nested timestamp shape {"datetime": "...", "formatted": "..."}.
type NestedDateTime = client.DateTime

// NestedRef Nested related-object reference, e.g. {"id": 3, "name": "X"}.
type NestedRef = client.Ref

// Id defines model for id.
type Id = int64
